# version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=elder
      - POSTGRES_USER=elder
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres
  
  # py-server:
  #   container_name: py-server
  #   build: .
  #   command: ["fastapi", "run","src/", "--port","8080","--reload"]
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://elder:elder@postgres:5432/fastapi-db
  #     - SECRET_KEY=f046009c5cf6f2d46f15dffa23737b09
  #     - JWT_ALGORITHM=HS256
